# pytest.ini
[pytest]
minversion = 6.0
testpaths = tests
addopts = -v -s --tb=short --asyncio-mode=auto
markers =
    slow: mark a test as slow.
    fast: mark a test as fast.
    api: mark tests related to API.
filterwarnings =
    error
    ignore::DeprecationWarning
    ignore::UserWarning
