"""add_created_at_to_staff_table

Revision ID: 5258ee05015f
Revises: 2025_04_24_add_staff_table
Create Date: 2025-04-24 12:16:27.975496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_04_24_add_created_at'
down_revision: Union[str, None] = '2025_04_24_add_staff_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('created_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'created_at')
    # ### end Alembic commands ###
