"""add is_active

Revision ID: 5c6d5879dc27
Revises: 25931673ae41
Create Date: 2025-11-18 09:10:00.302075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6d5879dc27'
down_revision: Union[str, None] = '25931673ae41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('staff', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.drop_column('staff', 'is_active')
    op.drop_column('product', 'is_active')
    # ### end Alembic commands ###
